### ISSUE TITLE
Kindly share a back-end

### ISSUE THREAD

**Issue by mindfulme** [sergeyCodenameOne/UberEatsClone#11]
Comment below if you have a back-end solution all in box for that app

**Comment by shai-almog** [comment]
If you want to fund an open source project to do that you can contact us via the chat at https://www.codenameone.com

**Comment by mindfulme** [comment]
https://codecanyon.net/item/stackfood-multi-restaurant-food-delivery-app-with-laravel-admin-and-restaurant-panel-v10/33571750 thats way better
